name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ballerina Install
      uses: ballerina-platform/ballerina-action/@1.1.1
    - name: Build with Maven
      run: mvn clean install
